#####################################
            // AUTH //
#####################################
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "pseudo": "SuperMan",
    "password": "password",
    "password2": "password",
    "email": "SuperMan@gmail.com"
    
}
###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "pseudo": "Gaetan",
    "password": "password",
    "password2":"password",
    "email": "gaetan.beurel@gmail.com"
    
}
###
GET http://localhost:5000/users/
Content-Type: application/json

###
GET http://localhost:5000/users/61a73c0e8aeca4e1384361f5
Content-Type: application/json
###


PUT http://localhost:5000/users/61a2731b935e8842504a6249
Content-Type: application/json

{
    "bio": "yo les gens cool !"
}
###
PATCH http://localhost:5000/users/follow/61a17169258007789ad08bcf
Content-Type: application/json

{
    "idToFollow": "61a17148258007789ad08bcb"  
}
###

PATCH http://localhost:5000/users/unfollow/61a17169258007789ad08bcf
Content-Type: application/json

{
    "idToUnFollow": "61a17148258007789ad08bcb"  
}
###



DELETE http://localhost:5000/users/61a889070d4b7506a800e089
###


GET http://localhost:5000/jwtid
Cookie:  access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTczYzBlOGFlY2E0ZTEzODQzNjFmNSIsImlhdCI6MTYzODM1Mjc5OCwiZXhwIjoxODk3NTUyNzk4fQ.WaHSewmHbF9EDTq1CR5Z9S5zo-qaQ5IGaSHhH5TO7EM; Max-Age=259200; Path=/; Expires=Sat, 04 Dec 2021 09:59:58 GMT; HttpOnly; Secure; SameSite=Lax


###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "password": "password",
    "email": "Jean.bon@gmail.com"
    
}
###

GET http://localhost:5000/auth/logout
Content-Type: application/json

{
    "password": "Bon",
    "email": "Premier.test@gmail.com"
    
}
###
############################################
                // POST //
############################################
GET http://localhost:5000/post
Content-Type: application/json
###
POST http://localhost:5000/post
Content-Type: application/json
Set-Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWY5OWQ3MDQ0MzczZTBiM2RmZGNjNSIsImlhdCI6MTY2MzA2Mjc1NCwiZXhwIjoxOTIyMjYyNzU0fQ.iH5Hv1FPEBj_osOo0dYmW_5cuF8Knk6f1v5iCJt-kJM; Max-Age=259200; Path=/; Expires=Fri, 16 Sep 2022 09:52:34 GMT; HttpOnly; Secure; SameSite=Lax

{
   "message": "bonjour, comment ça va !"
}
###
PUT http://localhost:5000/post/61a889070d4b7506a800e089
Content-Type: application/json

{
   "message": "yo les gros rigolo"
}
###
DELETE http://localhost:5000/post/61b1f0c651540b0657b30030
Content-Type: application/json

###
PATCH http://localhost:5000/post/like-post/61a889070d4b7506a800e089
Content-Type: application/json

{
   "id": "61a17148258007789ad08bcb"
}
###
PATCH http://localhost:5000/post/unlike-post/61a889070d4b7506a800e089
Content-Type: application/json

{
   "id": "61a17148258007789ad08bcb"
}
###

PATCH http://localhost:5000/post/comment-post/6319eda2429fffc9758a8e01
Content-Type: application/json

{
   "commenterId": "6319a647ee427a6e1dcffdf1",
   "commenterPseudo": "John",
   "text": "ça marche !"
}
###

PATCH http://localhost:5000/post/edit-comment-post/61a74a53ce551be9e572d756
Content-Type: application/json

{
   "commentId": "621503f8988b97635c654462",
   "text": "C'est trop bien!"
}
###

PATCH http://localhost:5000/post/delete-comment-post/61a889070d4b7506a800e089
Content-Type: application/json

{
   "commentId": "61a74a53ce551be9e572d756"
}
###

############################################
                // UPLOAD //
############################################


POST http://localhost:5000/upload
Content-Type: multipart/form-data
###